### PR TITLE
New multisync

### PR DESCRIPTION
**Pull request by mefjush**
Use the new multisync. I've tested the thing with the example.html. Iframe has been created fine, Rubicon's emily.html has been requested fine.
 
Can you check the the minified file? The diff looks strange. 
I've just run `make` Could anything go wrong?

### CODE REVIEW

**Comment by mefjush** [comment]
An example of changes in the minified file:
`"undefined"==typeof e.safeframe||0==e.safeframe?this.config.safeframe=!1`
got changed to
`void 0===e.safeframe||0==e.safeframe?this.config.safeframe=!1`
Different versions of uglyfier? (I've got uglify-js 3.0.25)
Maybe it's better if someone re-minifies this for me.

**Comment by tsturtew** [comment]
i have uglify 2.7.5, but maybe we should go for the newer one?
it shouldn't really matter, as each implementer should build his own version, and runs his own uglify i think

**Comment by mefjush** [comment]
So I'll merge then?

**Comment by tsturtew** [comment]
go ahead!

**Pull request merged**
